@startuml
top to bottom direction
skinparam linetype ortho

class AppExpression {
  + main(String[]): void
}
interface Expression {
  + calculerValeur(): double
}
class Nombre {
  - valeur: double
  + calculerValeur(): double
}
class Operation {
  - operateur: char
  + calculerValeur(): double
}

AppExpression   -.>  Nombre
AppExpression   -.>  Operation
Nombre          -.|>  Expression
Operation       -.|>  Expression
Operation       o--> "2" Expression
@enduml