@startuml
top to bottom direction
skinparam linetype ortho
skinparam nodesep 10
skinparam ranksep 50

class AppExpression {
  + main(String[]): void
}
interface Expression {
  + calculerValeur(): double
}
class Nombre {
  - valeur: double
}
class Operation {
  - operateur: char
}

AppExpression   -.>  Nombre
AppExpression   -.>  Operation
Nombre          -.|>  Expression
Operation       -.|>  Expression
Operation       o-- "2  " Expression
@enduml